user = "ubuntu"

[log]
	path = "/mnt/data/log/solana.log"
	
[reporting]
	solana_metrics_config = "host=https://metrics.solana.com:8086,db=tds,u=testnet_write,p=c4fa841aa918bf8274e3e2a44d77568d9861b3ea"
	
[ledger]
	path = "/mnt/data/ledger"
	accounts_path = "/mnt/acct/accounts"
	accounts_index_path = "/mnt/acct/accounts_index"
	limit_size = 50_000_000
	# Names and icons of peer validators will not be displayed in
	# the GUI unless the program-id index is enabled, which can be
	# done by setting
	account_indexes = ["program-id"]
	
[gossip]
	entrypoints = [
		"entrypoint.testnet.solana.com:8001",
		"entrypoint2.testnet.solana.com:8001",
		"entrypoint3.testnet.solana.com:8001",
	]
	port_check = false
	
[rpc]
	port = 8899
	full_api = true
	private = true
	
[snapshots]
	minimum_snapshot_download_speed = 52428800
	path = "/mnt/snap/snapshots"
	incremental_path = "/mnt/snap/snapshots_inc"
	
[consensus]
	identity_path = "/home/{user}/solana-tools/keys/validator-keypair.json"
	vote_account_path = "/home/{user}/solana-tools/keys/vote-account-testnet.json"
	authorized_voter_paths = ["/home/{user}/solana-tools/keys/validator-keypair-testnet.json"]
#	genesis_fetch = true
	poh_speed_test = false
	expected_genesis_hash = "4uhcVJyU9pJkvQyS88uRDiswHXSCkY3zQawwpjk2NsNY"
#	wait_for_supermajority_at_slot = 0
#	expected_bank_hash = ""
#	expected_shred_version = 0
	known_validators = [
		"5D1fNXzvv5NjV1ysLjirC4WY92RNsVH18vjmcszZd8on",
		"dDzy5SR3AXdYWVqbDEkVFdvSPCtS9ihF5kJkHCtXoFs",
		"Ft5fbkqNa76vnsjYNwjDZUXoTWpP7VYm3mtsaQckQADN",
		"eoKpUABi59aT4rR9HGS3LcMecfut9x7zJyodWWP43YQ",
		"9QxCLckBiJc783jnMvXZubK4wH86Eqqvashtrwvcsgkv",
	]
	
[layout]
	# 7442P by @bored_king
	# 7950X by @dumbbell_fr (shred_tile_count = 1 +gui +raid0)
#	affinitiy = "auto"
#	agave_affinity = "auto"
#	agave_unified_scheduler_handler_threads = 0
#	net_tile_count = 1
#	quic_tile_count = 1
#	resolv_tile_count = 1
#	verify_tile_count = 6
#	bank_tile_count = 4
	# Configure 2 shred tiles to handle the increased computational
	# overhead of shred destination calculation, which scales with
	# testnet's expanded validator peer set
	shred_tile_count = 2
	
	# CPU-based settings
	# 9124 by @bored_king
	# affinitiy = "0-14"
	# agave_affinity = "15-31"
	# verify_tile_count = 1
	# bank_tile_count = 1
	
	# 6226R by @rafa_tou
	# 7950X by @meyerbro
	# verify_tile_count = 2
	# bank_tile_count = 1
	
	# 5900X by @bored_king @matthiasstakingfacilities
	# verify_tile_count = 1
	# bank_tile_count = 1
	
	# 7413 by @cr1sp4rm1n
	# affinitiy = "1-22"
	# agave_affinity = "23-47"
	# bank_tile_count = 2
	
[tiles]
	[tiles.bundle]
		enabled = true
		url = "https://testnet.block-engine.jito.wtf"
		tip_distribution_program_addr = "F2Zu7QZiTYUhPd7u9ukRVwxh7B71oA3NMJcHuCHc29P2"
		tip_payment_program_addr = "GJHtFqM9agxPmkeKjHny6qiRKrXZALvvFGiKf11QE7hy"
		tip_distribution_authority = "7heQNXEtxSv3wV8sNbuQsDN5xNGbbpLvHGiyXuJxEf7n"
		commission_bps = 10000
		
#	[tiles.gui]
#		enabled = true
#		gui_listen_address = "127.0.0.1"
#		gui_listen_port = 80
